// ---------------------------------------------------------
// CanvasManager.cs
//
// ä½œæˆæ—¥:7æœˆå¾ŒåŠ
// ä½œæˆè€…:G2A118é½Šè—¤å¤§å¿—
//ã“ã®ã‚¹ã‚¯ãƒªãƒ—ãƒˆã¯ä»–ã®ã‚¹ã‚¯ãƒªãƒ—ãƒˆã¨ã®å¯†æ¥ãªé–¢ä¿‚ã§ã™
//ControllerSelectButtonã‚„ã‚‰ä½•ã‚„ã‚‰ã¾ã§
//UIã®ãƒ¡ã‚¤ãƒ³ã‚·ã‚¹ãƒ†ãƒ ã‹ã¤ã“ã®ã‚²ãƒ¼ãƒ ã®å‘½
// ---------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using UnityEngine.Splines;
using TMPro;

public class CanvasManager : MonoBehaviour {
    #region å¤‰æ•°
    // ãƒŸãƒ‹ã‚¹ã‚³ã‚¢è¡¨ç¤ºç”¨ã®TextMeshProUGUIé…åˆ—
    [SerializeField] private TextMeshProUGUI[] _miniScore;

    // ã‚¹ãƒ†ãƒ¼ã‚¸å¤‰æ›´ç”¨ã®ãƒãƒãƒ¼ã‚¸ãƒ£ãƒ¼
    [SerializeField, Header("ControllerSelectButton")] private ChengeStageManager _staChange;

    // ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©ãƒ¼ãƒœã‚¿ãƒ³ã®è¨­å®š
    [SerializeField, Header("ControllerSelectButton")] private ControllerSelectButton _button;

    // ã‚¿ã‚¤ãƒˆãƒ«ç”»é¢ã®å„ç¨®ãƒœã‚¿ãƒ³
    [Header("ã‚¿ã‚¤ãƒˆãƒ«ã®ãƒœã‚¿ãƒ³")]
    [SerializeField, Header("ã‚¹ã‚¿ãƒ¼ãƒˆãƒœã‚¿ãƒ³")] private Button _titleStart;
    [SerializeField, Header("ã‚²ãƒ¼ãƒ çµ‚äº†ãƒœã‚¿ãƒ³")] private Button _titleGameEnd;
    [SerializeField, Header("è¨­å®šãƒœã‚¿ãƒ³")] private Button _titleSetting;

    // ã‚²ãƒ¼ãƒ å†…ã§è¡¨ç¤ºã™ã‚‹ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®ã‚°ãƒ«ãƒ¼ãƒ—
    [SerializeField, Header("ãƒ•ã‚£ã‚¯ã‚·ãƒ§ãƒ³ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _fiction;
    [SerializeField, Header("ã‚¿ã‚¤ãƒˆãƒ«ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _titleObjs;
    [SerializeField, Header("ã‚«ã‚¦ãƒ³ãƒˆãƒ€ã‚¦ãƒ³ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _countObjs;
    [SerializeField, Header("ä¸€æ™‚åœæ­¢ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _menuObjs;
    [SerializeField, Header("ã‚²ãƒ¼ãƒ UIã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _gamePlayObjs;
    [SerializeField, Header("ãƒªã‚¶ãƒ«ãƒˆã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _resultObjs;
    [SerializeField, Header("è¨­å®šç”»é¢ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _settingObjs;
    [SerializeField, Header("ã‚ªãƒ¼ãƒ—ãƒ‹ãƒ³ã‚°ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _openingObjs;
    [SerializeField, Header("ã‚¨ãƒ³ãƒ‡ã‚£ãƒ³ã‚°ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _endingObjs;
    [SerializeField, Header("ã‚²ãƒ¼ãƒ ãƒ—ãƒ¬ã‚¤ä¸­ã«ä½¿ã†ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _gameObjs;
    [SerializeField, Header("ã‚²ãƒ¼ãƒ ãƒ—ãƒ¬ã‚¤ä¸­ã«ä½¿ã†ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ")] private GameObject[] _tutorialObjs;
    [SerializeField] private GameObject[] _none;  // ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆãŒç„¡ã„å ´åˆã®å‡¦ç†ç”¨
    [SerializeField] private SplineAnimate _spAnime;

    // ã‚¿ã‚°ã«åŸºã¥ã„ã¦ã‚·ãƒ¼ãƒ³é·ç§»ã‚’åˆ¶å¾¡ã™ã‚‹ãŸã‚ã®è¨­å®š
    [SerializeField, Header("ã‚¿ã‚¤ãƒˆãƒ«ã«è¡Œã‹ã›ãŸã„ã‚¿ã‚°"), Tag] private string _tagTitle;
    [SerializeField, Header("ã‚²ãƒ¼ãƒ ã«è¡Œã‹ã›ãŸã„ã‚¿ã‚°"), Tag] private string _tagGame;
    [SerializeField, Header("ã‚²ãƒ¼ãƒ ã«æˆ»ã™ã‚¿ã‚°"), Tag] private string _tagBackGame;
    [SerializeField, Header("è¨­å®šã«è¡Œã‹ã›ãŸã„ã‚¿ã‚°"), Tag] private string _tagSetting;
    [SerializeField, Header("ã‚²ãƒ¼ãƒ çµ‚äº†ã•ã›ãŸã„ã‚¿ã‚°"), Tag] private string _tagFinish;

    // ãƒªã‚¶ãƒ«ãƒˆç”»é¢ã®ç®¡ç†
    [SerializeField] private ResultManager _resultManager;

    // ã‚²ãƒ¼ãƒ ãƒ—ãƒ¬ã‚¤æ™‚é–“ã¨ã‚¿ã‚¤ãƒˆãƒ«ç”»é¢ã§ã®æ”¾ç½®æ™‚é–“ã®ã‚«ã‚¦ãƒ³ãƒˆ
    private float _gamePlayTime;

    // ã‚¿ã‚¤ãƒˆãƒ«ç”»é¢ã§ã®è‡ªå‹•é·ç§»ç”¨ã‚¿ã‚¤ãƒãƒ¼è¨­å®š
    [SerializeField, Header("ä½•ç§’æ“ä½œãŒãªã‹ã£ãŸã‚‰å‹•ç”»ã‚’æµã™ã‹")]
    private float _titleTime;
    private float _nowTitleTime;  // ã‚¿ã‚¤ãƒˆãƒ«ã§ã®çµŒéæ™‚é–“ã‚«ã‚¦ãƒ³ãƒˆ

    // å‹•ç”»å†ç”Ÿç”¨ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã¨BGMåˆ¶å¾¡
    [SerializeField] private GameObject _videoPlay;
    [SerializeField] private AudioSource _audioBGM;
    [SerializeField] private float _videotime;  // å‹•ç”»å†ç”Ÿæ™‚é–“

    // å„ç¨®çŠ¶æ…‹ã‚’ç®¡ç†ã™ã‚‹ãŸã‚ã®ãƒ•ãƒ©ã‚°
    private bool _isStartPush = true;

    // UIã®çŠ¶æ…‹ã‚’ç®¡ç†ã™ã‚‹ãŸã‚ã®åˆ—æŒ™ä½“
    private enum UIState {
        title,       // ã‚¿ã‚¤ãƒˆãƒ«ç”»é¢
        gamePlay,    // ã‚²ãƒ¼ãƒ ãƒ—ãƒ¬ã‚¤ä¸­
        result,      // ãƒªã‚¶ãƒ«ãƒˆç”»é¢
        menu,        // ãƒ¡ãƒ‹ãƒ¥ãƒ¼ï¼ˆãƒãƒ¼ã‚ºï¼‰ç”»é¢
        setting,     // è¨­å®šç”»é¢
        OP,          // ã‚ªãƒ¼ãƒ—ãƒ‹ãƒ³ã‚°ç”»é¢
        ED,          // ã‚¨ãƒ³ãƒ‡ã‚£ãƒ³ã‚°ç”»é¢
        Movie,       // ãƒ ãƒ¼ãƒ“ãƒ¼å†ç”Ÿä¸­
        Fiction,     // ãƒ•ã‚£ã‚¯ã‚·ãƒ§ãƒ³ã‚·ãƒ¼ãƒ³
        Tutorial,    //ãƒãƒ¥ãƒ¼ãƒˆãƒªã‚¢ãƒ«
    }

    // ç¾åœ¨ã¨å‰å›ã®UIçŠ¶æ…‹
    private UIState _state = UIState.Fiction;
    private UIState _prevState;

    // ç§»å‹•å¯èƒ½ã‹ã©ã†ã‹ã‚’ç®¡ç†ã™ã‚‹ãƒ•ãƒ©ã‚°
    private bool _canMove = false;
    #endregion
    #region ãƒ—ãƒ­ãƒ‘ãƒ†ã‚£
    #endregion
    #region ãƒ¡ã‚½ãƒƒãƒ‰
    /// <summary>
    /// æ›´æ–°å‡¦ç†
    /// </summary>
    void Update() {
        //ãƒã‚¦ã‚¹åŒæ™‚ã«æŠ¼ã™ã¨ã‚·ãƒ¼ãƒ³ã‚’ãƒªãƒ­ãƒ¼ãƒ‰
        if ((Input.GetMouseButton(0)&&Input.GetMouseButton(1))||(Input.GetMouseButton(1)&&Input.GetMouseButton(0))) {
            SceneManager.LoadScene(SceneManager.GetActiveScene().name);
        }
        //ãƒ•ã‚£ã‚¯ã‚·ãƒ§ãƒ³ã®æ™‚
        if (_state == UIState.Fiction) {
            //ã¾ã å‡¦ç†ã¯ãªã„
        }
        //ã‚¿ã‚¤ãƒˆãƒ«ã®æ™‚
        if (_state == UIState.title) {
            //ã‚¿ã‚¤ãƒˆãƒ«ã«ã„ã‚‹æ™‚é–“ã®è¨ˆæ¸¬
            _nowTitleTime += Time.deltaTime;
            //è¦å®šå€¤ã‚’è¶…ãˆãŸã‚‰
            if (_titleTime <= _nowTitleTime) {
                //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã‚’ãƒ ãƒ¼ãƒ“ãƒ¼ã«
                _state = UIState.Movie;
                //ã‚¿ã‚¤ãƒˆãƒ«ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’ç„¡åŠ¹åŒ–
                GameObjTrueFalse(_none, _titleObjs);
                //BGMã‚’æ­¢ã‚ã‚‹
                _audioBGM.Stop();
                //ãƒ“ãƒ‡ã‚ªå†ç”Ÿ
                _videoPlay.SetActive(true);
                //æ™‚é–“ã‚’ãƒªã‚»ãƒƒãƒˆ
                _nowTitleTime = 0;
            }
        }
        //ã‚²ãƒ¼ãƒ ä¸­ã®æ™‚
        if (_state == UIState.gamePlay) {
            //ãƒ—ãƒ¬ã‚¤æ™‚é–“åŠ ç®—
            _gamePlayTime += Time.deltaTime;
            //ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã«è¡Œã‹ã›ã‚‹ã®ã¯ä¸€æ—¦ç„¡ãã™

            //if (Input.GetKeyDown("joystick button 7")&&_isStartPush) {
            //    PlayToMenu();
            //    _isStartPush = false;
            //}
            //if (Input.GetKeyUp("joystick button 7")) {
            //    _isStartPush = true;
            //}
            _canMove = true;
        }
        //å‡¦ç†æ›¸ã„ã¦ã‚‹ã‘ã©ä»Šã¯ä½¿ã£ã¦ãªã„

        //if (_state == UIState.result) {
        //    if (Input.GetButtonDown("Cancel") && _isStartPush) {
        //        MenuOrResultToStart();
        //    }
        //    _resultManager.SetTexts();
        //    _canMove = false;
        //}
        //if (_state == UIState.menu) {
        //    if (Input.GetKeyDown("joystick button 7") && _isStartPush) {
        //        MenuToPlay();
        //        _isStartPush=false;
        //    }
        //    if (Input.GetKeyUp("joystick button 7")) {
        //        _isStartPush = true;
        //    }
        //    _canMove=false;
        //}
        if (_state == UIState.setting) {
            //Bãƒœã‚¿ãƒ³ã§æˆ»ã‚‹
            if (Input.GetButtonDown("Cancel")) {
                SettingToTitleOrMenu();
            }
        }
        //å‹•ç”»ä¸­ã®å‡¦ç†
        if (_state == UIState.Movie) {
            //æ™‚é–“åŠ ç®—
            _nowTitleTime += Time.deltaTime;
            //æ—¢å®šã®æ™‚é–“ã‚’è¶…ãˆã‚‹ã‹ä½•ã‹ãƒœã‚¿ãƒ³æŠ¼ã•ã‚ŒãŸã‚‰
            if (_nowTitleTime >= _videotime||Input.anyKeyDown) {
                //æœ€åˆã«æˆ»ã™
                _state = UIState.Fiction;
                //ãƒ•ã‚£ã‚¯ã‚·ãƒ§ãƒ³ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’æœ‰åŠ¹åŒ–
                GameObjTrueFalse(_fiction,_none);
                //å‹•ç”»ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’ç„¡åŠ¹åŒ–
                _videoPlay.SetActive(false);
                //æ™‚é–“ã®ãƒªã‚»ãƒƒãƒˆ
                _nowTitleTime = 0;
            }

        }
    }
    #region ã‚²ãƒ¼ãƒ ãƒ•ãƒ­ãƒ¼ã®æ ¹å¹¹
    //ãƒ•ã‚£ã‚¯ã‚·ãƒ§ãƒ³ğŸ‘‰ã‚ªãƒ¼ãƒ—ãƒ‹ãƒ³ã‚°ğŸ‘‰ã‚«ã‚¦ãƒ³ãƒˆãƒ€ã‚¦ãƒ³ğŸ‘‰ã‚²ãƒ¼ãƒ ä¸­ğŸ‘‰ã‚¨ãƒ³ãƒ‡ã‚£ãƒ³ã‚°ğŸ‘‰ãƒªã‚¶ãƒ«ãƒˆ
    //å¤–éƒ¨ã‹ã‚‰å‘¼ã³å‡ºã—ã¦ã„ã‚‹ã‚‚ã®ãŒå¤šã„ã§ã™ã€‚
    //ã‚²ãƒ¼ãƒ ä¸­ã«ã“ã‚Œã‚’æŒã£ãŸã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆä¸€å€‹ã—ã‹ãªã„ã‹ã‚‰ã‚·ãƒ³ã‚°ãƒ«ãƒˆãƒ³ã§ã‚‚ã‚ˆã‹ã£ãŸã‹ã‚‚


    /// <summary>
    /// ãƒ•ã‚£ã‚¯ã‚·ãƒ§ãƒ³ã‹ã‚‰ã‚¿ã‚¤ãƒˆãƒ«ã«è¡Œã‹ã›ã‚‹
    /// </summary>
    public void FictionToTitle() {
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ï¼šã‚¿ã‚¤ãƒˆãƒ«ã«
        _state = UIState.title;
        GameObjTrueFalse( _titleObjs,_fiction);
    }

    /// <summary>
    /// ã‚¿ã‚¤ãƒˆãƒ«ã‹ã‚‰ã‚ªãƒ¼ãƒ—ãƒ‹ãƒ³ã‚°ã¸
    /// </summary>
    private void TitleToOP() {
        GameObjTrueFalse(_openingObjs, _titleObjs);
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ï¼šã‚ªãƒ¼ãƒ—ãƒ‹ãƒ³ã‚°
        _state = UIState.OP;
    }
    public void OPToTutorial() {
        GameObjTrueFalse(_tutorialObjs, _openingObjs);
        _state=UIState.Tutorial;
    }
    private void TutorialToCount() {
        GameObjTrueFalse(_countObjs, _tutorialObjs);
    }

    /// <summary>
    /// ã‚ªãƒ¼ãƒ—ãƒ‹ãƒ³ã‚°ã‹ã‚‰ã‚«ã‚¦ãƒ³ãƒˆãƒ€ã‚¦ãƒ³ã«é·ç§»
    /// </summary>
    public void OPtoCount() {
        GameObjTrueFalse(_countObjs, _openingObjs);
        ///////////////////////////////////////////
    }

    /// <summary>
    /// ã‚ªãƒ¼ãƒ—ãƒ‹ãƒ³ã‚°ï¼ˆã‚«ã‚¦ãƒ³ãƒˆãƒ€ã‚¦ãƒ³çŠ¶æ…‹ï¼‰ã‹ã‚‰ã‚²ãƒ¼ãƒ ç”»é¢ã¸
    /// </summary>
    public void OPToGamePlay() {
        GameObjTrueFalse(_gamePlayObjs, _openingObjs);
        GameObjTrueFalse(_gameObjs, _openingObjs);
        //ã‚¹ãƒ—ãƒ©ã‚¤ãƒ³ã‚¢ãƒ‹ãƒ¡ãƒ¼ãƒˆã‚’æœ‰åŠ¹åŒ–
        //åˆæœŸã§ç„¡åŠ¹åŒ–ã—ã¨ã‹ãªã„ã¨ã‚¨ãƒ‡ã‚£ã‚¿ãƒ¼ä¸Šã§å‹•ã
        _spAnime.enabled = true;
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ï¼šã‚²ãƒ¼ãƒ ä¸­ã«
        _state = UIState.gamePlay;
        //ã‚¹ãƒ†ãƒ¼ã‚¸ã”ã¨ã®ãƒªã‚¯ã‚¨ã‚¹ãƒˆãƒœã‚¤ã‚¹ã‚’æµã™
        _staChange.GameStartVoice();
    }

    /// <summary>
    /// ã‚²ãƒ¼ãƒ ãƒ—ãƒ¬ã‚¤ã‹ã‚‰ã‚¨ãƒ³ãƒ‡ã‚£ãƒ³ã‚°ã¸
    /// </summary>
    public void PlayToED() {
        GameObjTrueFalse(_endingObjs, _gamePlayObjs);
        GameObjTrueFalse(_endingObjs, _gameObjs);
        //ã‚¨ãƒ³ãƒ‡ã‚£ãƒ³ã‚°ç”¨ã®BGMé³´ã‚‰ã—ã¦ã‚‚ã‚‰ã†
        _button.StartBGM();
        //ã‚¹ãƒ—ãƒ©ã‚¤ãƒ³ã‚¢ãƒ‹ãƒ¡ãƒ¼ãƒˆã‚’ç„¡åŠ¹åŒ–
        _spAnime.enabled = false;
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ï¼šã‚¨ãƒ³ãƒ‡ã‚£ãƒ³ã‚°ã«
        _state = UIState.ED;
        //å„ã‚¹ãƒ†ãƒ¼ã‚¸ã«å‡ºã‚‹ãƒªã‚¶ãƒ«ãƒˆã‚’ç„¡åŠ¹åŒ–
        //ã‚‚ã—ã‹ã—ãŸã‚‰ä½¿ã£ã¦ãªã„ã‹ã‚‚
        foreach (TextMeshProUGUI item in _miniScore) {
            item.enabled = false;
        }
    }

    /// <summary>
    /// ã‚¨ãƒ³ãƒ‡ã‚£ãƒ³ã‚°ã‹ã‚‰ãƒªã‚¶ãƒ«ãƒˆ
    /// </summary>
    public void EDToResult() {
        GameObjTrueFalse(_resultObjs, _endingObjs);
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ï¼šãƒªã‚¶ãƒ«ãƒˆã¸
        _state = UIState.result;
    }
    /// <summary>
    /// ãƒªã‚¶ãƒ«ãƒˆã‹ã‚‰ã‚¿ã‚¤ãƒˆãƒ«ã¸
    /// </summary>
    public void MenuOrResultToStart() {
        //ãƒªãƒ­ãƒ¼ãƒ‰ã—ã¦ã‚²ãƒ¼ãƒ ã®ãƒªã‚»ãƒƒãƒˆã‚’è¡Œã†
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
        //ã‚‚ã—ã‹ã—ãŸã‚‰ã‚„ã‚‰ãªãã¦ã„ã„ã‹ã‚‚
        _state = UIState.Fiction;
    }

    #endregion
    #region é–‹ç™ºæ®µéšã§ä½¿ã‚ã‚Œãªããªã£ãŸç‰©ãŸã¡
    /// <summary>
    /// ã‚¿ã‚¤ãƒˆãƒ«ã‹ã‚‰ã‚²ãƒ¼ãƒ ç”»é¢ã¸
    /// </summary>
    private void TitleToGamePlay()
    {

        //OPToGamePlay()ã¨TitleToOP()ã«ä»•äº‹ã¨ã‚‰ã‚ŒãŸ

        GameObjTrueFalse(_gamePlayObjs, _titleObjs);
        GameObjTrueFalse(_gameObjs, _titleObjs);
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ï¼šã‚²ãƒ¼ãƒ ä¸­ã«
        _state = UIState.gamePlay;
    }
    /// <summary>
    /// ã‚²ãƒ¼ãƒ ç”»é¢ã‹ã‚‰ãƒãƒ¼ã‚ºã¸
    /// </summary>
    private void PlayToMenu() {
        //æœ€åˆã¨ã‚¹ãƒ†ãƒ¼ã‚¸æ§‹æˆå¤‰ã‚ã£ãŸã‹ã‚‰ä¸€æ—¦ç„¡è¦–
        GameObjTrueFalse(_menuObjs, _gamePlayObjs);
        GameObjTrueFalse(_menuObjs, _gameObjs);
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ï¼šãƒãƒ¼ã‚ºã«
        _state = UIState.menu;
    }
    /// <summary>
    /// ãƒãƒ¼ã‚ºã‹ã‚‰ã‚²ãƒ¼ãƒ ç”»é¢ã¸
    /// </summary>
    private void MenuToPlay() {
        // PlayToMenu()ã¨åŒã˜ãä¸€æ—¦ç„¡è¦–
        print("menuã‹ã‚‰æˆ»ã‚‹ã‚ˆ");
        GameObjTrueFalse(_gamePlayObjs, _menuObjs);
        GameObjTrueFalse(_gameObjs, _menuObjs);
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ï¼šã‚²ãƒ¼ãƒ ä¸­ã«
        _state = UIState.gamePlay;
    }
    #endregion
    #region è¨­å®šé–¢ä¿‚
    /// <summary>
    /// ã‚¿ã‚¤ãƒˆãƒ«ã‹ãƒãƒ¼ã‚ºã‹ã‚‰è¨­å®šç”»é¢ã¸
    /// </summary>
    private void TitleOrMenuToSetting() {
        //ã‚¿ã‚¤ãƒˆãƒ«ã‹ãƒãƒ¼ã‚ºã‹ã‚’åŒºåˆ¥ã™ã‚‹ãŸã‚ã«å‰ã®ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã‚’ä¿å­˜
        _prevState = _state;
        //å‰ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ãŒã‚¿ã‚¤ãƒˆãƒ«ã®å ´åˆ
        if (_prevState == UIState.title) {
            GameObjTrueFalse(_settingObjs, _titleObjs);
        }
        //å‰ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ãŒãƒãƒ¼ã‚ºã®å ´åˆ
        else if (_prevState == UIState.menu) {
            GameObjTrueFalse(_settingObjs, _menuObjs);
        }
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ï¼šè¨­å®šã«
        _state = UIState.setting;
    }
    /// <summary>
    /// è¨­å®šç”»é¢ã‹ã‚‰ã‚¿ã‚¤ãƒˆãƒ«ã‹ãƒãƒ¼ã‚ºã¸
    /// </summary>
    private void SettingToTitleOrMenu() {
        //å‰ã®ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ãŒã‚¿ã‚¤ãƒˆãƒ«ã®å ´åˆ
        if (_prevState == UIState.title) {
            GameObjTrueFalse(_titleObjs, _settingObjs);
        }
        //å‰ã®ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ãŒãƒãƒ¼ã‚ºã®å ´åˆ
        else if (_prevState == UIState.menu) {
            GameObjTrueFalse(_menuObjs, _settingObjs);
        }
        //ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã‚’æ›´æ–°
        _state = _prevState;
    }
    #endregion
    #region ãã®ä»–system
    /// <summary>
    /// ã‚²ãƒ¼ãƒ çµ‚äº†
    /// </summary>
    private void GameFinish()
    {
#if UNITY_EDITOR
        // Unityã‚¨ãƒ‡ã‚£ã‚¿å†…ã§ã®çµ‚äº†å‡¦ç†
        UnityEditor.EditorApplication.isPlaying = false;
#else
        // ãƒ“ãƒ«ãƒ‰ã•ã‚ŒãŸã‚²ãƒ¼ãƒ ã®çµ‚äº†å‡¦ç†
        Application.Quit();
#endif
    }
  
    /// <summary>
    /// æŠ¼ã•ã‚ŒãŸæ™‚ã®å‡¦ç†ã‚’æ±ºã‚ã‚‹
    /// </summary>
    public void OnClickSw(string tagname) {
        if (tagname == _tagGame) {
            //ã‚¿ã‚¤ãƒˆãƒ«ã‹ã‚‰ã‚²ãƒ¼ãƒ ã¸
            TitleToOP();
        } else if (tagname == _tagSetting) {
            //ã‚¿ã‚¤ãƒˆãƒ«orãƒãƒ¼ã‚ºã‹ã‚‰è¨­å®šã¸
            TitleOrMenuToSetting();
        } else if (tagname == _tagFinish) {
            //ã‚²ãƒ¼ãƒ ã‚’çµ‚ã‚ã‚‰ã›ã‚‹
            GameFinish();
        } else if (tagname == _tagTitle) {
            //ã‚¿ã‚¤ãƒˆãƒ«ã«æˆ»ã‚‹
            MenuOrResultToStart();
        } else if (tagname == _tagBackGame) {
            //ã‚¿ã‚¤ãƒˆãƒ«ã«æˆ»ã‚‹
            //å¤šåˆ†å†—é•·ãªæ›¸ãæ–¹
            MenuOrResultToStart();
        }

    }

    /// <summary>
    /// æœ‰åŠ¹åŒ–ã¨ç„¡åŠ¹åŒ–ã®ã‚¹ã‚¤ãƒƒãƒ
    /// å¼•æ•°ï¼‘ï¼š>æœ‰åŠ¹åŒ–ã—ãŸã„ã‚²ãƒ¼ãƒ ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆé…åˆ—ã€€å¼•æ•°ï¼’ï¼šç„¡åŠ¹åŒ–ã—ãŸã„ã‚²ãƒ¼ãƒ ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆé…åˆ—
    /// </summary>
    /// <param name="trueObjects">æœ‰åŠ¹åŒ–ã—ãŸã„ã‚²ãƒ¼ãƒ ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆé…åˆ—</param>
    /// <param name="falseObjects">ç„¡åŠ¹åŒ–ã—ãŸã„ã‚²ãƒ¼ãƒ ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆé…åˆ—</param>
    private void GameObjTrueFalse(GameObject[] trueObjects, GameObject[] falseObjects)
    {
        //ç„¡åŠ¹åŒ–
        foreach (GameObject obj in falseObjects) {
            obj.SetActive(false);
        }
        //æœ‰åŠ¹åŒ–
        foreach (GameObject obj in trueObjects) {
            obj.SetActive(true);
        }
       
    }
    #endregion
    #region è¿”ã‚Šå€¤ã‚ã‚Š
    /// <summary>
    /// ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹å…±æœ‰
    /// </summary>
    /// <returns>ç¾åœ¨ã®ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã‚’stringå‹ã§è¿”ã™</returns>
    public string StateSet() {
        return _state.ToString();
    }
    /// <summary>
    /// å‹•ã„ã¦ã„ã„ã‹ã®ã‚¹ã‚¤ãƒƒãƒå…±æœ‰
    /// </summary>
    /// <returns>trueãªã‚‰å‹•ã„ã¦ã€falseãªã‚‰æ­¢ã‚ã‚‹</returns>
    public bool CanMove() {
        return _canMove;
    }
    /// <summary>
    /// ã‚²ãƒ¼ãƒ ãƒ—ãƒ¬ã‚¤æ™‚é–“ã‚’å…±æœ‰
    /// </summary>
    /// <returns>ç¾åœ¨ã®ãƒ—ãƒ¬ã‚¤æ™‚é–“ã‚’é€ã‚‹</returns>
    public float GamePlayTime() {
        return _gamePlayTime;
    }
    #endregion
#endregion
}